# Generated by Django 2.2.9 on 2020-05-23 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=300)),
                ('matricula', models.CharField(max_length=30)),
                ('datanasc', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('nome_responsavel', models.CharField(max_length=300)),
                ('telefone_responsavel', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CampoExperiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'campo experiencia',
                'verbose_name_plural': 'campos experiencias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=300)),
                ('endereco', models.CharField(max_length=500)),
                ('diretor', models.CharField(max_length=300)),
                ('cnpj', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(max_length=2)),
                ('user', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=300)),
                ('cpf', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('datanasc', models.DateField()),
                ('user', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=16)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='entidades.Escola')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=500)),
                ('descricao', models.TextField()),
                ('periodo', models.CharField(max_length=500)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='entidades.Professor')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.TextField()),
                ('codigo', models.CharField(max_length=100)),
                ('campo_experiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='entidades.CampoExperiencia')),
            ],
            options={
                'verbose_name': 'objetivo',
                'verbose_name_plural': 'objetivos',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('avaliacao', models.CharField(max_length=10)),
                ('observacao', models.TextField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='entidades.Aluno')),
                ('campo_experiencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='entidades.CampoExperiencia')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='entidades.Objetivo')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='entidades.Professor')),
            ],
            options={
                'verbose_name': 'avaliacao',
                'verbose_name_plural': 'avaliacoes',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='entidades.Professor'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='entidades.Turma'),
        ),
    ]
